export const browseJSON = {
  data: {
    banner: {
      movieData: {
        adult: false,
        backdrop_path: '/4gV6FOT4mEF4JaOmurO1kQSQ0Zl.jpg',
        genre_ids: [28, 12, 14],
        id: 572802,
        original_language: 'en',
        original_title: 'Aquaman and the Lost Kingdom',
        overview:
          "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
        popularity: 8227.52,
        poster_path: '/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg',
        release_date: '2023-12-20',
        title: 'Aquaman and the Lost Kingdom',
        video: false,
        vote_average: 7.001,
        vote_count: 1063
      },
      videoData: {
        iso_639_1: 'en',
        iso_3166_1: 'US',
        name: 'Official Trailer',
        key: 'UGc5Tzz19UY',
        site: 'YouTube',
        size: 2160,
        type: 'Trailer',
        official: true,
        published_at: '2023-09-20T17:37:05.000Z',
        id: '651299c18e2ba600c7cceb61'
      }
    },
    carousel: [
      {
        keyword: 'upcoming',
        title: 'Upcoming',
        firebase_data: false,
        ui_data: true,
        data: [
          {
            adult: false,
            backdrop_path: '/r1eCvALF6fN7anVYL8Zn7PaceD1.jpg',
            genre_ids: [35, 10751, 14],
            id: 787699,
            original_language: 'en',
            original_title: 'Wonka',
            overview:
              'Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.',
            popularity: 3413.306,
            poster_path: '/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
            release_date: '2023-12-06',
            title: 'Wonka',
            video: false,
            vote_average: 7.246,
            vote_count: 1611
          },
          {
            adult: false,
            backdrop_path: '/meyhnvssZOPPjud4F1CjOb4snET.jpg',
            genre_ids: [16, 12, 35, 10751, 28],
            id: 940551,
            original_language: 'en',
            original_title: 'Migration',
            overview:
              'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.',
            popularity: 2391.227,
            poster_path: '/ldfCF9RhR40mppkzmftxapaHeTo.jpg',
            release_date: '2023-12-06',
            title: 'Migration',
            video: false,
            vote_average: 7.852,
            vote_count: 344
          },
          {
            adult: false,
            backdrop_path: '/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg',
            genre_ids: [878, 10749, 35],
            id: 792307,
            original_language: 'en',
            original_title: 'Poor Things',
            overview:
              'Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.',
            popularity: 690.01,
            poster_path: '/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
            release_date: '2023-12-07',
            title: 'Poor Things',
            video: false,
            vote_average: 8.2,
            vote_count: 520
          },
          {
            adult: false,
            backdrop_path: '/a0GM57AnJtNi7lMOCamniiyV10W.jpg',
            genre_ids: [16, 12, 14],
            id: 508883,
            original_language: 'ja',
            original_title: '君たちはどう生きるか',
            overview:
              'While the Second World War rages, the teenage Mahito, haunted by his mother\'s tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy\'s mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the "long-awaited one."',
            popularity: 644.374,
            poster_path: '/jDQPkgzerGophKRRn7MKm071vCU.jpg',
            release_date: '2023-07-14',
            title: 'The Boy and the Heron',
            video: false,
            vote_average: 7.461,
            vote_count: 855
          },
          {
            adult: false,
            backdrop_path: '/p9DKeXp6FPJtAQ1k13Z4zPWrCbN.jpg',
            genre_ids: [18],
            id: 1058694,
            original_language: 'en',
            original_title: 'Radical',
            overview:
              'In a Mexican border town plagued by neglect, corruption, and violence, a frustrated teacher tries a radical new method to break through his students’ apathy and unlock their curiosity, their potential… and maybe even their genius.',
            popularity: 592.568,
            poster_path: '/eSatbygYZp8ooprBHZdb6GFZxGB.jpg',
            release_date: '2023-10-19',
            title: 'Radical',
            video: false,
            vote_average: 8.5,
            vote_count: 117
          },
          {
            adult: false,
            backdrop_path: '/9uNCYl2qmg16FLarg3n3Ea0PBIG.jpg',
            genre_ids: [27, 53],
            id: 1216784,
            original_language: 'en',
            original_title: 'Sunrise',
            overview:
              'When an ex-cop named Fallon returns to the scene of a horrific crime, the residents of a rural town soon discover that this dark visitor is really a vampire who feeds on blood and fear. After he is befriended by a kind immigrant family, the instinctive killer is faced with a choice between revenge and redemption.',
            popularity: 581.373,
            poster_path: '/4aRvg2ybz646gciX5M6qaclunC2.jpg',
            release_date: '2024-01-19',
            title: 'Sunrise',
            video: false,
            vote_average: 7.65,
            vote_count: 10
          },
          {
            adult: false,
            backdrop_path: '/kWyQh9fCrgcMfhqZmqtp89Q0TrT.jpg',
            genre_ids: [35, 10749],
            id: 1072790,
            original_language: 'en',
            original_title: 'Anyone But You',
            overview:
              'After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.',
            popularity: 522.938,
            poster_path: '/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg',
            release_date: '2023-12-21',
            title: 'Anyone But You',
            video: false,
            vote_average: 7.379,
            vote_count: 145
          },
          {
            adult: false,
            backdrop_path: '/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg',
            genre_ids: [28, 53, 18],
            id: 866398,
            original_language: 'en',
            original_title: 'The Beekeeper',
            overview:
              'One man’s campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.',
            popularity: 514.114,
            poster_path: '/A7EByudX0eOzlkQ2FIbogzyazm2.jpg',
            release_date: '2024-01-10',
            title: 'The Beekeeper',
            video: false,
            vote_average: 7.488,
            vote_count: 205
          },
          {
            adult: false,
            backdrop_path: '/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg',
            genre_ids: [28, 35],
            id: 897087,
            original_language: 'en',
            original_title: 'Freelance',
            overview:
              'An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.',
            popularity: 397.708,
            poster_path: '/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg',
            release_date: '2023-10-05',
            title: 'Freelance',
            video: false,
            vote_average: 6.5,
            vote_count: 493
          },
          {
            adult: false,
            backdrop_path: '/klb3yODwKMRle19EcvdeSatEZL7.jpg',
            genre_ids: [27, 53],
            id: 1072342,
            original_language: 'en',
            original_title: 'Night Swim',
            overview:
              "Forced into early retirement by a degenerative illness, former baseball player Ray Waller moves into a new house with his wife and two children. He hopes that the backyard swimming pool will be fun for the kids and provide physical therapy for himself. However, a dark secret from the home's past soon unleashes a malevolent force that drags the family into the depths of inescapable terror.",
            popularity: 353.316,
            poster_path: '/gSkfBGdxdialBMM7P02V4hcI6Ij.jpg',
            release_date: '2024-01-03',
            title: 'Night Swim',
            video: false,
            vote_average: 5.92,
            vote_count: 143
          },
          {
            adult: false,
            backdrop_path: '/7NRGAtu8E4343NSKwhkgmVRDINw.jpg',
            genre_ids: [27, 9648],
            id: 507089,
            original_language: 'en',
            original_title: "Five Nights at Freddy's",
            overview:
              "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
            popularity: 350.437,
            poster_path: '/7BpNtNfxuocYEVREzVMO75hso1l.jpg',
            release_date: '2023-10-25',
            title: "Five Nights at Freddy's",
            video: false,
            vote_average: 7.721,
            vote_count: 3266
          },
          {
            adult: false,
            backdrop_path: '/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg',
            genre_ids: [28, 18],
            id: 678512,
            original_language: 'en',
            original_title: 'Sound of Freedom',
            overview:
              'The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.',
            popularity: 337.829,
            poster_path: '/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg',
            release_date: '2023-07-03',
            title: 'Sound of Freedom',
            video: false,
            vote_average: 8.054,
            vote_count: 1860
          },
          {
            adult: false,
            backdrop_path: '/du11oPPbEoDnUpiREO5tUg47rJd.jpg',
            genre_ids: [18, 36],
            id: 365620,
            original_language: 'en',
            original_title: 'Ferrari',
            overview:
              'Set during the summer of 1957. Ex-racecar driver, Enzo Ferrari, is in crisis. Bankruptcy stalks the company he and his wife, Laura, built from nothing ten years earlier. Their tempestuous marriage struggles with the mourning for one son and the acknowledgement of another.',
            popularity: 303.855,
            poster_path: '/xBFyJHvXCTgf9Vmq5uCnXRHrMQ4.jpg',
            release_date: '2023-12-14',
            title: 'Ferrari',
            video: false,
            vote_average: 6.698,
            vote_count: 258
          },
          {
            adult: false,
            backdrop_path: '/mv8M0PqQYicndU7TGgBAHrI4uUo.jpg',
            genre_ids: [27, 53],
            id: 744857,
            original_language: 'es',
            original_title: 'Cuando acecha la maldad',
            overview:
              'Residents of a small rural town discover that a demon is about to be born among them. They desperately try to escape before the evil is born, but it may be too late.',
            popularity: 255.487,
            poster_path: '/2gimJ06p9tVR4P6jacZWcLcNEwA.jpg',
            release_date: '2023-10-05',
            title: 'When Evil Lurks',
            video: false,
            vote_average: 7.353,
            vote_count: 473
          },
          {
            adult: false,
            backdrop_path: '/hQJR85HLngbthcWvaBXsaNCntvl.jpg',
            genre_ids: [18, 10749],
            id: 1226281,
            original_language: 'tl',
            original_title: 'Pantasya ni Tami',
            overview:
              'Tami, with the help of her fubu photographer, Ken, sells sexy photos of herself. When she meets her fan, Gelo, who loves her as she is, she is torn whether to leave cosplaying or leave Gelo.',
            popularity: 252.684,
            poster_path: '/iej9tjZsnWbfn6BirakJAygfaEq.jpg',
            release_date: '2024-02-02',
            title: 'Pantasya ni Tami',
            video: false,
            vote_average: 0,
            vote_count: 0
          },
          {
            adult: false,
            backdrop_path: '/fGe1ej335XbqN1j9teoDpofpbLX.jpg',
            genre_ids: [18, 9648, 80],
            id: 915935,
            original_language: 'fr',
            original_title: "Anatomie d'une chute",
            overview:
              'A woman is suspected of her husband’s murder, and their blind son faces a moral dilemma as the sole witness.',
            popularity: 216.439,
            poster_path: '/kQs6keheMwCxJxrzV83VUwFtHkB.jpg',
            release_date: '2023-08-13',
            title: 'Anatomy of a Fall',
            video: false,
            vote_average: 7.8,
            vote_count: 768
          },
          {
            adult: false,
            backdrop_path: '/mpIpHN7DJprENGiSvxOaG5mLzht.jpg',
            genre_ids: [35],
            id: 673593,
            original_language: 'en',
            original_title: 'Mean Girls',
            overview:
              'New student Cady Heron is welcomed into the top of the social food chain by the elite group of popular girls called ‘The Plastics,’ ruled by the conniving queen bee Regina George and her minions Gretchen and Karen. However, when Cady makes the major misstep of falling for Regina’s ex-boyfriend Aaron Samuels, she finds herself prey in Regina’s crosshairs. As Cady sets to take down the group’s apex predator with the help of her outcast friends Janis and Damian, she must learn how to stay true to herself while navigating the most cutthroat jungle of all: high school.',
            popularity: 190.508,
            poster_path: '/fbbj3viSUDEGT1fFFMNpHP1iUjw.jpg',
            release_date: '2024-01-10',
            title: 'Mean Girls',
            video: false,
            vote_average: 6.6,
            vote_count: 102
          },
          {
            adult: false,
            backdrop_path: '/jkKVLzLWjSvTnc84VzeljhSy6j8.jpg',
            genre_ids: [10749, 18],
            id: 820525,
            original_language: 'en',
            original_title: 'After Everything',
            overview:
              'Besieged by writer’s block and the crushing breakup with Tessa, Hardin travels to Portugal in search of a woman he wronged in the past – and to find himself. Hoping to win back Tessa, he realizes he needs to change his ways before he can make the ultimate commitment.',
            popularity: 185.69,
            poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
            release_date: '2023-09-13',
            title: 'After Everything',
            video: false,
            vote_average: 6.922,
            vote_count: 666
          },
          {
            adult: false,
            backdrop_path: '/g8kCHQzfogy1t1dE9nPBtiFkz64.jpg',
            genre_ids: [53, 878, 18],
            id: 729854,
            original_language: 'ko',
            original_title: '콘크리트 유토피아',
            overview:
              'The world has been reduced to rubble by a massive earthquake. While no one knows for sure how far the ruins stretch, or what the cause of the earthquake may be, in the heart of Seoul there is only one apartment building left standing. It is called Hwang Gung Apartments. As time passes, outsiders start coming in to Hwang Gung Apartments trying to escape the extreme cold. Before long, the apartment residents are unable to cope with the increasing numbers. Feeling a threat to their very survival, the residents enact a special measure.',
            popularity: 176.75,
            poster_path: '/4l68KHxnPSow8MvnGUpjqLzJtLJ.jpg',
            release_date: '2023-08-09',
            title: 'Concrete Utopia',
            video: false,
            vote_average: 7.074,
            vote_count: 61
          },
          {
            adult: false,
            backdrop_path: '/j64H7GlYSarltRHJOl75jxLTRV6.jpg',
            genre_ids: [18, 53],
            id: 1026436,
            original_language: 'en',
            original_title: "Miller's Girl",
            overview:
              'A talented young writer embarks on a creative odyssey when her teacher assigns a project that entangles them both in an increasingly complex web.',
            popularity: 174.664,
            poster_path: '/aygFQeDmmtlArzo8epmsOg9mz9f.jpg',
            release_date: '2024-01-18',
            title: "Miller's Girl",
            video: false,
            vote_average: 7.5,
            vote_count: 11
          }
        ]
      },
      {
        keyword: 'popular',
        title: 'Popular',
        firebase_data: false,
        ui_data: true,
        data: [
          {
            adult: false,
            backdrop_path: '/4gV6FOT4mEF4JaOmurO1kQSQ0Zl.jpg',
            genre_ids: [28, 12, 14],
            id: 572802,
            original_language: 'en',
            original_title: 'Aquaman and the Lost Kingdom',
            overview:
              "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
            popularity: 8227.52,
            poster_path: '/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg',
            release_date: '2023-12-20',
            title: 'Aquaman and the Lost Kingdom',
            video: false,
            vote_average: 6.986,
            vote_count: 1056
          },
          {
            adult: false,
            backdrop_path: '/r1eCvALF6fN7anVYL8Zn7PaceD1.jpg',
            genre_ids: [35, 10751, 14],
            id: 787699,
            original_language: 'en',
            original_title: 'Wonka',
            overview:
              'Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.',
            popularity: 3413.306,
            poster_path: '/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
            release_date: '2023-12-06',
            title: 'Wonka',
            video: false,
            vote_average: 7.243,
            vote_count: 1607
          },
          {
            adult: false,
            backdrop_path: '/meyhnvssZOPPjud4F1CjOb4snET.jpg',
            genre_ids: [16, 12, 35, 10751, 28],
            id: 940551,
            original_language: 'en',
            original_title: 'Migration',
            overview:
              'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.',
            popularity: 2391.227,
            poster_path: '/ldfCF9RhR40mppkzmftxapaHeTo.jpg',
            release_date: '2023-12-06',
            title: 'Migration',
            video: false,
            vote_average: 7.835,
            vote_count: 339
          },
          {
            adult: false,
            backdrop_path: '/tLxjbT5ROZRwYcpNT3nfQbqkApk.jpg',
            genre_ids: [878, 12, 28],
            id: 609681,
            original_language: 'en',
            original_title: 'The Marvels',
            overview:
              'Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.',
            popularity: 2073.816,
            poster_path: '/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg',
            release_date: '2023-11-08',
            title: 'The Marvels',
            video: false,
            vote_average: 6.416,
            vote_count: 1303
          },
          {
            adult: false,
            backdrop_path: '/ehumsuIBbgAe1hg343oszCLrAfI.jpg',
            genre_ids: [16, 10751, 14, 12],
            id: 1022796,
            original_language: 'en',
            original_title: 'Wish',
            overview:
              'Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.',
            popularity: 2305.88,
            poster_path: '/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg',
            release_date: '2023-11-13',
            title: 'Wish',
            video: false,
            vote_average: 6.61,
            vote_count: 495
          },
          {
            adult: false,
            backdrop_path: '/vdpE5pjJVql5aD6pnzRqlFmgxXf.jpg',
            genre_ids: [18, 36],
            id: 906126,
            original_language: 'es',
            original_title: 'La sociedad de la nieve',
            overview:
              'On October 13, 1972, Uruguayan Air Force Flight 571, chartered to take a rugby team to Chile, crashes into a glacier in the heart of the Andes.',
            popularity: 1060.455,
            poster_path: '/2e853FDVSIso600RqAMunPxiZjq.jpg',
            release_date: '2023-12-13',
            title: 'Society of the Snow',
            video: false,
            vote_average: 8.109,
            vote_count: 1489
          },
          {
            adult: false,
            backdrop_path: '/rz8GGX5Id2hCW1KzAIY4xwbQw1w.jpg',
            genre_ids: [28, 35, 80],
            id: 955916,
            original_language: 'en',
            original_title: 'Lift',
            overview:
              'An international heist crew, led by Cyrus Whitaker, race to lift $500 million in gold from a passenger plane at 40,000 feet.',
            popularity: 1034.924,
            poster_path: '/gma8o1jWa6m0K1iJ9TzHIiFyTtI.jpg',
            release_date: '2024-01-10',
            title: 'Lift',
            video: false,
            vote_average: 6.479,
            vote_count: 581
          },
          {
            adult: false,
            backdrop_path: '/ba9TgAO4I8RyA2LljzR3MspHaM9.jpg',
            genre_ids: [28, 878, 53],
            id: 799155,
            original_language: 'hi',
            original_title: 'Attack',
            overview:
              'With the Parliament under siege, India’s first super soldier Arjun Shergill is tasked to get hold of the terrorists in the nick of time, save the Prime Minister from their clutches and stop a dirty bomb from exploding and destroying Delhi. Will Arjun succeed in his mission?',
            popularity: 1086.307,
            poster_path: '/5jGKbYuZtdxSNOocI6ZziQeiY4n.jpg',
            release_date: '2022-04-01',
            title: 'Attack',
            video: false,
            vote_average: 7.507,
            vote_count: 74
          },
          {
            adult: false,
            backdrop_path: '/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg',
            genre_ids: [36, 10752, 18],
            id: 753342,
            original_language: 'en',
            original_title: 'Napoleon',
            overview:
              'An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.',
            popularity: 1071.439,
            poster_path: '/vcZWJGvB5xydWuUO1vaTLI82tGi.jpg',
            release_date: '2023-11-22',
            title: 'Napoleon',
            video: false,
            vote_average: 6.517,
            vote_count: 1483
          },
          {
            adult: false,
            backdrop_path: '/xCt3Ha6hhHep5pwiW2FSenC59Gn.jpg',
            genre_ids: [28, 10752],
            id: 965571,
            original_language: 'ru',
            original_title: 'Время патриотов',
            overview:
              "The brothers Sultan and Bekzat Ibrayev are serving faithfully in the Armed Forces of Kazakhstan, and at the same time they are in family disagreement. Sultan is a valiant intelligence officer and Bekzat is a talented fighter pilot. While an international terrorist organization prepares a carefully planned attack on the country's strategically important facilities, the brothers have to face not only a mortal threat, but also face a family confrontation related to their dead father. Circumstances force them to unite in order to save human lives, and the brothers eventually understand that their homeland and family are the most valuable thing they have.",
            popularity: 729.292,
            poster_path: '/A4QM6oF4UNNhQh1f9pRdXvyKW5s.jpg',
            release_date: '2022-04-28',
            title: 'Patriots Time',
            video: false,
            vote_average: 9.778,
            vote_count: 9
          },
          {
            adult: false,
            backdrop_path: '/adNMDatnEnIEo4LUo1KyhouP6VA.jpg',
            genre_ids: [28, 18],
            id: 1212073,
            original_language: 'de',
            original_title: '60 Minuten',
            overview:
              'Desperate to keep custody of his daughter, a mixed martial arts fighter abandons a big match and races across Berlin to attend her birthday party.',
            popularity: 1018.483,
            poster_path: '/jojfbnIHGsRpodIood3OQoqA45Y.jpg',
            release_date: '2024-01-19',
            title: 'Sixty Minutes',
            video: false,
            vote_average: 6.849,
            vote_count: 142
          },
          {
            adult: false,
            backdrop_path: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
            genre_ids: [18, 36],
            id: 872585,
            original_language: 'en',
            original_title: 'Oppenheimer',
            overview:
              "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
            popularity: 658.114,
            poster_path: '/ptpr0kGAckfQkJeJIt8st5dglvd.jpg',
            release_date: '2023-07-19',
            title: 'Oppenheimer',
            video: false,
            vote_average: 8.115,
            vote_count: 6419
          },
          {
            adult: false,
            backdrop_path: '/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg',
            genre_ids: [878, 10749, 35],
            id: 792307,
            original_language: 'en',
            original_title: 'Poor Things',
            overview:
              'Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.',
            popularity: 690.01,
            poster_path: '/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
            release_date: '2023-12-07',
            title: 'Poor Things',
            video: false,
            vote_average: 8.204,
            vote_count: 518
          },
          {
            adult: false,
            backdrop_path: '/p9DKeXp6FPJtAQ1k13Z4zPWrCbN.jpg',
            genre_ids: [18],
            id: 1058694,
            original_language: 'en',
            original_title: 'Radical',
            overview:
              'In a Mexican border town plagued by neglect, corruption, and violence, a frustrated teacher tries a radical new method to break through his students’ apathy and unlock their curiosity, their potential… and maybe even their genius.',
            popularity: 592.568,
            poster_path: '/eSatbygYZp8ooprBHZdb6GFZxGB.jpg',
            release_date: '2023-10-19',
            title: 'Radical',
            video: false,
            vote_average: 8.509,
            vote_count: 115
          },
          {
            adult: false,
            backdrop_path: '/yl2GfeCaPoxChcGyM5p7vYp1CKS.jpg',
            genre_ids: [28, 35, 10749],
            id: 848187,
            original_language: 'en',
            original_title: 'Role Play',
            overview:
              'Emma has a wonderful husband and two kids in the suburbs of New Jersey – she also has a secret life as an assassin for hire – a secret that her husband David discovers when the couple decide to spice up their marriage with a little role play.',
            popularity: 646.838,
            poster_path: '/7MhXiTmTl16LwXNPbWCmqxj7UxH.jpg',
            release_date: '2023-12-14',
            title: 'Role Play',
            video: false,
            vote_average: 6.069,
            vote_count: 231
          },
          {
            adult: false,
            backdrop_path: '/a0GM57AnJtNi7lMOCamniiyV10W.jpg',
            genre_ids: [16, 12, 14],
            id: 508883,
            original_language: 'ja',
            original_title: '君たちはどう生きるか',
            overview:
              'While the Second World War rages, the teenage Mahito, haunted by his mother\'s tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy\'s mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the "long-awaited one."',
            popularity: 644.374,
            poster_path: '/jDQPkgzerGophKRRn7MKm071vCU.jpg',
            release_date: '2023-07-14',
            title: 'The Boy and the Heron',
            video: false,
            vote_average: 7.455,
            vote_count: 853
          },
          {
            adult: false,
            backdrop_path: '/6OnoMgGFuZ921eV8v8yEyXoag19.jpg',
            genre_ids: [28, 53],
            id: 1211957,
            original_language: 'en',
            original_title: 'The Painter',
            overview:
              'An ex-CIA operative is thrown back into a dangerous world when a mysterious woman from his past resurfaces. Now exposed and targeted by a relentless killer and a rogue black ops program, he must rely on skills he thought he left behind in a high-stakes game of survival.',
            popularity: 535.138,
            poster_path: '/UZ0ydgbXtnrq8xZCI5lHVXVcH9.jpg',
            release_date: '2024-01-05',
            title: 'The Painter',
            video: false,
            vote_average: 7.069,
            vote_count: 36
          },
          {
            adult: false,
            backdrop_path: '/ruKNVJFViAyR4jguVboFXTskMOe.jpg',
            genre_ids: [53, 28, 27],
            id: 1028703,
            original_language: 'en',
            original_title: 'The OctoGames',
            overview:
              '8 contestants compete in 8 deadly, classic children\'s games. They seek fame beyond their wildest dreams, competing for the chance to take over the YouTube channel of the famous yet elusive masked YouTuber known only as "JaxPro".',
            popularity: 615.116,
            poster_path: '/qGz5rffXhegQH5PGUDiObqoOt06.jpg',
            release_date: '2022-10-07',
            title: 'The OctoGames',
            video: false,
            vote_average: 5.694,
            vote_count: 49
          },
          {
            adult: false,
            backdrop_path: '/9uNCYl2qmg16FLarg3n3Ea0PBIG.jpg',
            genre_ids: [27, 53],
            id: 1216784,
            original_language: 'en',
            original_title: 'Sunrise',
            overview:
              'When an ex-cop named Fallon returns to the scene of a horrific crime, the residents of a rural town soon discover that this dark visitor is really a vampire who feeds on blood and fear. After he is befriended by a kind immigrant family, the instinctive killer is faced with a choice between revenge and redemption.',
            popularity: 581.373,
            poster_path: '/4aRvg2ybz646gciX5M6qaclunC2.jpg',
            release_date: '2024-01-19',
            title: 'Sunrise',
            video: false,
            vote_average: 7.65,
            vote_count: 10
          },
          {
            adult: false,
            backdrop_path: '/dvNrgldueQciabkYmlCnyhmaPoO.jpg',
            genre_ids: [28, 9648, 53, 27],
            id: 899445,
            original_language: 'en',
            original_title: 'Deep Fear',
            overview:
              'A solo trip aboard a yacht takes a terrifying turn when a woman encounters three drug traffickers clinging to the shattered remains of a boat. They soon force her to dive into shark-infested waters to retrieve kilos of cocaine from the sunken wreck.',
            popularity: 564.381,
            poster_path: '/wjYxOR1S4yonkLP9NTFpFTCTL7d.jpg',
            release_date: '2023-10-18',
            title: 'Deep Fear',
            video: false,
            vote_average: 5.841,
            vote_count: 91
          }
        ]
      },
      {
        keyword: 'played',
        title: 'Recently Played for ${user}',
        firebase_data: true,
        ui_data: false
      },
      {
        keyword: 'top_rated',
        title: 'Top Rated',
        firebase_data: false,
        ui_data: true,
        data: [
          {
            adult: false,
            backdrop_path: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
            genre_ids: [18, 80],
            id: 278,
            original_language: 'en',
            original_title: 'The Shawshank Redemption',
            overview:
              'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
            popularity: 128.87,
            poster_path: '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            release_date: '1994-09-23',
            title: 'The Shawshank Redemption',
            video: false,
            vote_average: 8.711,
            vote_count: 25444
          },
          {
            adult: false,
            backdrop_path: '/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg',
            genre_ids: [18, 80],
            id: 238,
            original_language: 'en',
            original_title: 'The Godfather',
            overview:
              'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
            popularity: 128.217,
            poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
            release_date: '1972-03-14',
            title: 'The Godfather',
            video: false,
            vote_average: 8.708,
            vote_count: 19367
          },
          {
            adult: false,
            backdrop_path: '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
            genre_ids: [18, 80],
            id: 240,
            original_language: 'en',
            original_title: 'The Godfather Part II',
            overview:
              'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
            popularity: 82.795,
            poster_path: '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
            release_date: '1974-12-20',
            title: 'The Godfather Part II',
            video: false,
            vote_average: 8.6,
            vote_count: 11682
          },
          {
            adult: false,
            backdrop_path: '/3f92DMBTFqr3wgXpfxzrb0qv8nG.jpg',
            genre_ids: [18, 36, 10752],
            id: 424,
            original_language: 'en',
            original_title: "Schindler's List",
            overview:
              'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
            popularity: 119.949,
            poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
            release_date: '1993-12-15',
            title: "Schindler's List",
            video: false,
            vote_average: 8.572,
            vote_count: 15057
          },
          {
            adult: false,
            backdrop_path: '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
            genre_ids: [18],
            id: 389,
            original_language: 'en',
            original_title: '12 Angry Men',
            overview:
              "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
            popularity: 57.811,
            poster_path: '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
            release_date: '1957-04-10',
            title: '12 Angry Men',
            video: false,
            vote_average: 8.546,
            vote_count: 7985
          },
          {
            adult: false,
            backdrop_path: '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
            genre_ids: [35, 18, 10749],
            id: 19404,
            original_language: 'hi',
            original_title: 'दिलवाले दुल्हनिया ले जायेंगे',
            overview:
              'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
            popularity: 33.943,
            poster_path: '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
            release_date: '1995-10-20',
            title: 'Dilwale Dulhania Le Jayenge',
            video: false,
            vote_average: 8.543,
            vote_count: 4325
          },
          {
            adult: false,
            backdrop_path: '/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg',
            genre_ids: [16, 10751, 14],
            id: 129,
            original_language: 'ja',
            original_title: '千と千尋の神隠し',
            overview:
              'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
            popularity: 115.526,
            poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
            release_date: '2001-07-20',
            title: 'Spirited Away',
            video: false,
            vote_average: 8.539,
            vote_count: 15441
          },
          {
            adult: false,
            backdrop_path: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
            genre_ids: [18, 28, 80, 53],
            id: 155,
            original_language: 'en',
            original_title: 'The Dark Knight',
            overview:
              'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
            popularity: 117.42,
            poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
            release_date: '2008-07-16',
            title: 'The Dark Knight',
            video: false,
            vote_average: 8.514,
            vote_count: 31352
          },
          {
            adult: false,
            backdrop_path: '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
            genre_ids: [35, 53, 18],
            id: 496243,
            original_language: 'ko',
            original_title: '기생충',
            overview:
              "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
            popularity: 87.408,
            poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
            release_date: '2019-05-30',
            title: 'Parasite',
            video: false,
            vote_average: 8.513,
            vote_count: 17018
          },
          {
            adult: false,
            backdrop_path: '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
            genre_ids: [14, 18, 80],
            id: 497,
            original_language: 'en',
            original_title: 'The Green Mile',
            overview:
              "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
            popularity: 85.092,
            poster_path: '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
            release_date: '1999-12-10',
            title: 'The Green Mile',
            video: false,
            vote_average: 8.511,
            vote_count: 16409
          },
          {
            adult: false,
            backdrop_path: '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
            genre_ids: [10749, 16, 18],
            id: 372058,
            original_language: 'ja',
            original_title: '君の名は。',
            overview:
              'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
            popularity: 95.33,
            poster_path: '/q719jXXEzOoYaps6babgKnONONX.jpg',
            release_date: '2016-08-26',
            title: 'Your Name.',
            video: false,
            vote_average: 8.5,
            vote_count: 10709
          },
          {
            adult: false,
            backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
            genre_ids: [53, 80],
            id: 680,
            original_language: 'en',
            original_title: 'Pulp Fiction',
            overview:
              "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
            popularity: 76.175,
            poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
            release_date: '1994-09-10',
            title: 'Pulp Fiction',
            video: false,
            vote_average: 8.489,
            vote_count: 26550
          },
          {
            adult: false,
            backdrop_path: '/9DeGfFIqjph5CBFVQrD6wv9S7rR.jpg',
            genre_ids: [12, 14, 28],
            id: 122,
            original_language: 'en',
            original_title: 'The Lord of the Rings: The Return of the King',
            overview:
              "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
            popularity: 103.879,
            poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
            release_date: '2003-12-01',
            title: 'The Lord of the Rings: The Return of the King',
            video: false,
            vote_average: 8.478,
            vote_count: 22940
          },
          {
            adult: false,
            backdrop_path: '/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
            genre_ids: [35, 18, 10749],
            id: 13,
            original_language: 'en',
            original_title: 'Forrest Gump',
            overview:
              'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
            popularity: 85.683,
            poster_path: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
            release_date: '1994-06-23',
            title: 'Forrest Gump',
            video: false,
            vote_average: 8.477,
            vote_count: 26078
          },
          {
            adult: false,
            backdrop_path: '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
            genre_ids: [37],
            id: 429,
            original_language: 'it',
            original_title: 'Il buono, il brutto, il cattivo',
            overview:
              'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
            popularity: 63.035,
            poster_path: '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
            release_date: '1966-12-22',
            title: 'The Good, the Bad and the Ugly',
            video: false,
            vote_average: 8.47,
            vote_count: 8039
          },
          {
            adult: false,
            backdrop_path: '/sw7mordbZxgITU877yTpZCud90M.jpg',
            genre_ids: [18, 80],
            id: 769,
            original_language: 'en',
            original_title: 'GoodFellas',
            overview:
              'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
            popularity: 64.183,
            poster_path: '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
            release_date: '1990-09-12',
            title: 'GoodFellas',
            video: false,
            vote_average: 8.468,
            vote_count: 12119
          },
          {
            adult: false,
            backdrop_path: '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
            genre_ids: [28, 18],
            id: 346,
            original_language: 'ja',
            original_title: '七人の侍',
            overview:
              "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
            popularity: 42.613,
            poster_path: '/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg',
            release_date: '1954-04-26',
            title: 'Seven Samurai',
            video: false,
            vote_average: 8.459,
            vote_count: 3380
          },
          {
            adult: false,
            backdrop_path: '/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg',
            genre_ids: [16, 18, 10752],
            id: 12477,
            original_language: 'ja',
            original_title: '火垂るの墓',
            overview:
              'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
            popularity: 0.6,
            poster_path: '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
            release_date: '1988-04-15',
            title: 'Grave of the Fireflies',
            video: false,
            vote_average: 8.457,
            vote_count: 5070
          },
          {
            adult: false,
            backdrop_path: '/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg',
            genre_ids: [35, 18],
            id: 637,
            original_language: 'it',
            original_title: 'La vita è bella',
            overview:
              'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
            popularity: 51.23,
            poster_path: '/6tEJnof1DKWPnl5lzkjf0FVv7oB.jpg',
            release_date: '1997-12-20',
            title: 'Life Is Beautiful',
            video: false,
            vote_average: 8.456,
            vote_count: 12528
          },
          {
            adult: false,
            backdrop_path: '/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg',
            genre_ids: [18, 10749],
            id: 11216,
            original_language: 'it',
            original_title: 'Nuovo Cinema Paradiso',
            overview:
              "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
            popularity: 31.638,
            poster_path: '/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg',
            release_date: '1988-11-17',
            title: 'Cinema Paradiso',
            video: false,
            vote_average: 8.45,
            vote_count: 4098
          }
        ]
      },
      { keyword: 'saved', title: 'My List', firebase_data: true, ui_data: false },
      {
        keyword: 'now_playing',
        title: 'Now Playing',
        firebase_data: false,
        ui_data: true,
        data: [
          {
            adult: false,
            backdrop_path: '/4gV6FOT4mEF4JaOmurO1kQSQ0Zl.jpg',
            genre_ids: [28, 12, 14],
            id: 572802,
            original_language: 'en',
            original_title: 'Aquaman and the Lost Kingdom',
            overview:
              "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
            popularity: 8227.52,
            poster_path: '/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg',
            release_date: '2023-12-20',
            title: 'Aquaman and the Lost Kingdom',
            video: false,
            vote_average: 7.001,
            vote_count: 1063
          },
          {
            adult: false,
            backdrop_path: '/r1eCvALF6fN7anVYL8Zn7PaceD1.jpg',
            genre_ids: [35, 10751, 14],
            id: 787699,
            original_language: 'en',
            original_title: 'Wonka',
            overview:
              'Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.',
            popularity: 3413.306,
            poster_path: '/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
            release_date: '2023-12-06',
            title: 'Wonka',
            video: false,
            vote_average: 7.249,
            vote_count: 1613
          },
          {
            adult: false,
            backdrop_path: '/meyhnvssZOPPjud4F1CjOb4snET.jpg',
            genre_ids: [16, 12, 35, 10751, 28],
            id: 940551,
            original_language: 'en',
            original_title: 'Migration',
            overview:
              'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.',
            popularity: 2391.227,
            poster_path: '/ldfCF9RhR40mppkzmftxapaHeTo.jpg',
            release_date: '2023-12-06',
            title: 'Migration',
            video: false,
            vote_average: 7.859,
            vote_count: 348
          },
          {
            adult: false,
            backdrop_path: '/ehumsuIBbgAe1hg343oszCLrAfI.jpg',
            genre_ids: [16, 10751, 14, 12],
            id: 1022796,
            original_language: 'en',
            original_title: 'Wish',
            overview:
              'Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.',
            popularity: 2305.88,
            poster_path: '/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg',
            release_date: '2023-11-13',
            title: 'Wish',
            video: false,
            vote_average: 6.639,
            vote_count: 501
          },
          {
            adult: false,
            backdrop_path: '/vdpE5pjJVql5aD6pnzRqlFmgxXf.jpg',
            genre_ids: [18, 36],
            id: 906126,
            original_language: 'es',
            original_title: 'La sociedad de la nieve',
            overview:
              'On October 13, 1972, Uruguayan Air Force Flight 571, chartered to take a rugby team to Chile, crashes into a glacier in the heart of the Andes.',
            popularity: 1060.455,
            poster_path: '/2e853FDVSIso600RqAMunPxiZjq.jpg',
            release_date: '2023-12-13',
            title: 'Society of the Snow',
            video: false,
            vote_average: 8.114,
            vote_count: 1495
          },
          {
            adult: false,
            backdrop_path: '/rz8GGX5Id2hCW1KzAIY4xwbQw1w.jpg',
            genre_ids: [28, 35, 80],
            id: 955916,
            original_language: 'en',
            original_title: 'Lift',
            overview:
              'An international heist crew, led by Cyrus Whitaker, race to lift $500 million in gold from a passenger plane at 40,000 feet.',
            popularity: 1034.924,
            poster_path: '/gma8o1jWa6m0K1iJ9TzHIiFyTtI.jpg',
            release_date: '2024-01-10',
            title: 'Lift',
            video: false,
            vote_average: 6.497,
            vote_count: 584
          },
          {
            adult: false,
            backdrop_path: '/adNMDatnEnIEo4LUo1KyhouP6VA.jpg',
            genre_ids: [28, 18],
            id: 1212073,
            original_language: 'de',
            original_title: '60 Minuten',
            overview:
              'Desperate to keep custody of his daughter, a mixed martial arts fighter abandons a big match and races across Berlin to attend her birthday party.',
            popularity: 1018.483,
            poster_path: '/jojfbnIHGsRpodIood3OQoqA45Y.jpg',
            release_date: '2024-01-19',
            title: 'Sixty Minutes',
            video: false,
            vote_average: 6.928,
            vote_count: 146
          },
          {
            adult: false,
            backdrop_path: '/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg',
            genre_ids: [878, 10749, 35],
            id: 792307,
            original_language: 'en',
            original_title: 'Poor Things',
            overview:
              'Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.',
            popularity: 690.01,
            poster_path: '/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
            release_date: '2023-12-07',
            title: 'Poor Things',
            video: false,
            vote_average: 8.206,
            vote_count: 522
          },
          {
            adult: false,
            backdrop_path: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
            genre_ids: [18, 36],
            id: 872585,
            original_language: 'en',
            original_title: 'Oppenheimer',
            overview:
              "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
            popularity: 658.114,
            poster_path: '/ptpr0kGAckfQkJeJIt8st5dglvd.jpg',
            release_date: '2023-07-19',
            title: 'Oppenheimer',
            video: false,
            vote_average: 8.115,
            vote_count: 6426
          },
          {
            adult: false,
            backdrop_path: '/yl2GfeCaPoxChcGyM5p7vYp1CKS.jpg',
            genre_ids: [28, 35, 10749],
            id: 848187,
            original_language: 'en',
            original_title: 'Role Play',
            overview:
              'Emma has a wonderful husband and two kids in the suburbs of New Jersey – she also has a secret life as an assassin for hire – a secret that her husband David discovers when the couple decide to spice up their marriage with a little role play.',
            popularity: 646.838,
            poster_path: '/7MhXiTmTl16LwXNPbWCmqxj7UxH.jpg',
            release_date: '2023-12-14',
            title: 'Role Play',
            video: false,
            vote_average: 6.098,
            vote_count: 235
          },
          {
            adult: false,
            backdrop_path: '/a0GM57AnJtNi7lMOCamniiyV10W.jpg',
            genre_ids: [16, 12, 14],
            id: 508883,
            original_language: 'ja',
            original_title: '君たちはどう生きるか',
            overview:
              'While the Second World War rages, the teenage Mahito, haunted by his mother\'s tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy\'s mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the "long-awaited one."',
            popularity: 644.374,
            poster_path: '/jDQPkgzerGophKRRn7MKm071vCU.jpg',
            release_date: '2023-07-14',
            title: 'The Boy and the Heron',
            video: false,
            vote_average: 7.463,
            vote_count: 858
          },
          {
            adult: false,
            backdrop_path: '/9uNCYl2qmg16FLarg3n3Ea0PBIG.jpg',
            genre_ids: [27, 53],
            id: 1216784,
            original_language: 'en',
            original_title: 'Sunrise',
            overview:
              'When an ex-cop named Fallon returns to the scene of a horrific crime, the residents of a rural town soon discover that this dark visitor is really a vampire who feeds on blood and fear. After he is befriended by a kind immigrant family, the instinctive killer is faced with a choice between revenge and redemption.',
            popularity: 581.373,
            poster_path: '/4aRvg2ybz646gciX5M6qaclunC2.jpg',
            release_date: '2024-01-19',
            title: 'Sunrise',
            video: false,
            vote_average: 7.864,
            vote_count: 11
          },
          {
            adult: false,
            backdrop_path: '/6OnoMgGFuZ921eV8v8yEyXoag19.jpg',
            genre_ids: [28, 53],
            id: 1211957,
            original_language: 'en',
            original_title: 'The Painter',
            overview:
              'An ex-CIA operative is thrown back into a dangerous world when a mysterious woman from his past resurfaces. Now exposed and targeted by a relentless killer and a rogue black ops program, he must rely on skills he thought he left behind in a high-stakes game of survival.',
            popularity: 535.138,
            poster_path: '/UZ0ydgbXtnrq8xZCI5lHVXVcH9.jpg',
            release_date: '2024-01-05',
            title: 'The Painter',
            video: false,
            vote_average: 7.188,
            vote_count: 40
          },
          {
            adult: false,
            backdrop_path: '/kWyQh9fCrgcMfhqZmqtp89Q0TrT.jpg',
            genre_ids: [35, 10749],
            id: 1072790,
            original_language: 'en',
            original_title: 'Anyone But You',
            overview:
              'After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.',
            popularity: 522.938,
            poster_path: '/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg',
            release_date: '2023-12-21',
            title: 'Anyone But You',
            video: false,
            vote_average: 7.401,
            vote_count: 147
          },
          {
            adult: false,
            backdrop_path: '/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg',
            genre_ids: [28, 53, 18],
            id: 866398,
            original_language: 'en',
            original_title: 'The Beekeeper',
            overview:
              'One man’s campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.',
            popularity: 514.114,
            poster_path: '/A7EByudX0eOzlkQ2FIbogzyazm2.jpg',
            release_date: '2024-01-10',
            title: 'The Beekeeper',
            video: false,
            vote_average: 7.5,
            vote_count: 206
          },
          {
            adult: false,
            backdrop_path: '/e0M3WVJm4nBrAg0LbJq0gdKi3U7.jpg',
            genre_ids: [18, 878, 28],
            id: 695721,
            original_language: 'en',
            original_title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
            overview:
              '64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.',
            popularity: 493.852,
            poster_path: '/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg',
            release_date: '2023-11-15',
            title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
            video: false,
            vote_average: 7.225,
            vote_count: 1609
          },
          {
            adult: false,
            backdrop_path: '/ay0PJQZizDXk0pzhoGX4v7K9h7A.jpg',
            genre_ids: [28, 53],
            id: 1214314,
            original_language: 'en',
            original_title: 'One More Shot',
            overview:
              'Following the attack on the black site in Poland, Navy SEAL Jake Harris is ordered to escort terrorist suspect Amin Mansur to Washington D.C. for interrogation. Before the prisoner transfer process is complete, though, the airport is attacked by a group of heavily armed, well-trained mercenaries.',
            popularity: 443.158,
            poster_path: '/nQ1BQg4yMdlYSHvHZgwladzy7EF.jpg',
            release_date: '2024-01-12',
            title: 'One More Shot',
            video: false,
            vote_average: 6.744,
            vote_count: 80
          },
          {
            adult: false,
            backdrop_path: '/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg',
            genre_ids: [878, 27, 28],
            id: 940721,
            original_language: 'ja',
            original_title: 'ゴジラ-1.0',
            overview:
              'In postwar Japan, a new terror rises. Will the devastated people be able to survive... let alone fight back?',
            popularity: 395.03,
            poster_path: '/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg',
            release_date: '2023-11-03',
            title: 'Godzilla Minus One',
            video: false,
            vote_average: 7.904,
            vote_count: 368
          },
          {
            adult: false,
            backdrop_path: '/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg',
            genre_ids: [16, 10751, 10402, 14, 35],
            id: 901362,
            original_language: 'en',
            original_title: 'Trolls Band Together',
            overview:
              "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
            popularity: 392.924,
            poster_path: '/lxoPJR6eR5nd6nHSKIkEIV4FQWe.jpg',
            release_date: '2023-10-12',
            title: 'Trolls Band Together',
            video: false,
            vote_average: 7.2,
            vote_count: 580
          },
          {
            adult: false,
            backdrop_path: '/rVJfabCz1ViynQCEz54MRqdZig1.jpg',
            genre_ids: [16, 878, 28],
            id: 1155089,
            original_language: 'en',
            original_title: 'Justice League: Crisis on Infinite Earths Part One',
            overview:
              'Death is coming. Worse than death: oblivion. Not just for our Earth, but for everyone, everywhere, in every universe! Against this ultimate destruction, the mysterious Monitor has gathered the greatest team of Super Heroes ever assembled. But what can the combined might of Superman, Wonder Woman, Batman, The Flash, Green Lantern and hundreds of Super Heroes from multiple Earths even do to save all of reality from an unstoppable antimatter armageddon?!',
            popularity: 384.449,
            poster_path: '/zR6C66EDklgTPLHRSmmMt5878MR.jpg',
            release_date: '2024-01-09',
            title: 'Justice League: Crisis on Infinite Earths Part One',
            video: false,
            vote_average: 7.739,
            vote_count: 136
          }
        ]
      },
      { keyword: 'searched', title: 'Recommendations', firebase_data: true, ui_data: false }
    ]
  }
};
